### PR TITLE
Adding sound support.

### PR DESCRIPTION
**Pull request by drio**
Discussion about this [here](https://github.com/mbostock/stack/issues/9).

### CODE REVIEW

**Comment by mbostock** [comment]
I’m not inclined to add this to the library given that you can pretty easily implement it using the existing API (using activate / deactivate events plus a key event listener).

**Comment by drio** [comment]
But you would still need all the `sounds.js` logic.
I can rewrite it so we use activate/deactivate events. Would that be fine? If not, that's alright, please close both
the PR and the [issue](https://github.com/mbostock/stack/issues/9).

Thanks for looking into this Mike.

**Comment by mbostock** [comment]
Right, but I think that would make more sense in a separate library + example. If I can, I’d rather keep this library as small & simple as possible.

**Comment by drio** [comment]
Ok, makes sense. I will keep it in my account. I will send you the link, just in case you want to add it to the stacks' readme.

**Comment by drio** [comment]
How can I attach my listeners to the activate/deactivate events from outside stack? Should we expose event?

**Comment by mbostock** [comment]
`stack.on("activate", function(i) { console.log(d3.event, i); })`

**Comment by drio** [comment]
Thanks Mike. Ah.. you are actually [rebinding](https://github.com/mbostock/stack/blob/gh-pages/stack.v0.js#L216) `on` to the stack object.

**Pull request closed without merging**
